import Link from "next/link";
import { notFound } from "next/navigation";

const tools: Record<string, { name: string; category: string; description: string; pricing: string; features: string[] }> = {
  jasper:{name:"Jasper",category:"Marketing",pricing:"Paid",description:"The AI copilot for marketing teams who need to create high-performing, on-brand content at scale.",features:["Brand voice and knowledge","Campaign content generation","Collaboration for marketing teams"]},
  "notion-ai":{name:"Notion AI",category:"Writing & Editing",pricing:"Freemium",description:"Write, summarize, and find answers across your team workspace without leaving the flow of work.",features:["AI meeting notes","Enterprise search","Writing and translation"]},
  "intercom-fin":{name:"Intercom Fin",category:"Customer Service",pricing:"Paid",description:"An AI customer service agent that answers questions and resolves complex support conversations.",features:["Natural conversation","Knowledge-base answers","Human handoff"]},
  "canva-magic-studio":{name:"Canva Magic Studio",category:"Design & Creative",pricing:"Freemium",description:"AI-powered creative tools for making campaign-ready visual assets.",features:["Magic design","Background generation","Video creation"]},
  clay:{name:"Clay",category:"Sales",pricing:"Freemium",description:"A go-to-market platform for researching companies and personalizing outbound.",features:["Data enrichment","Account research","Personalized outreach"]},
  "zapier-agents":{name:"Zapier Agents",category:"Operations",pricing:"Freemium",description:"Build AI agents that automate work across the business tools your team uses.",features:["App integrations","Automated workflows","Custom instructions"]},
  grammarly:{name:"Grammarly",category:"Writing & Editing",pricing:"Freemium",description:"AI writing assistance that helps every team member communicate with clarity.",features:["Context-aware suggestions","Tone adjustment","Team style guides"]},
  "hubspot-breeze":{name:"HubSpot Breeze",category:"Marketing",pricing:"Paid",description:"AI embedded across marketing, sales, and service for better customer experiences.",features:["Content assistant","Lead intelligence","Service agent"]},
};
export function generateStaticParams(){return Object.keys(tools).map(slug=>({slug}))}
export default async function ToolDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const tool=tools[slug];if(!tool)notFound();return <main style={{minHeight:"100vh",background:"#050506",color:"#f7f7f8"}}><header className="nav"><Link className="brand" href="/"><i>✦</i>AIORBIT</Link><nav><Link className="active" href="/">Business AI</Link><a>Leaderboard</a><a>Resources</a></nav></header><section style={{maxWidth:1000,margin:"auto",padding:"48px 24px 100px"}}><Link href="/#directory" style={{color:"#aaa5ff",fontSize:12}}>← Back to Business AI</Link><div style={{display:"flex",gap:22,padding:"42px 0",borderBottom:"1px solid #252931"}}><div style={{width:82,height:82,borderRadius:18,display:"grid",placeItems:"center",fontSize:36,fontWeight:800,background:"linear-gradient(140deg,#9664ff,#5941d6)"}}>{tool.name[0]}</div><div><p className="eyebrow">{tool.category.toUpperCase()} · AI TOOL</p><h1 style={{fontSize:44,letterSpacing:"-.05em",margin:"0 0 10px"}}>{tool.name}</h1><p style={{color:"#9aa1ad",fontSize:16,lineHeight:1.6,maxWidth:650}}>{tool.description}</p><button className="primary">Visit website ↗</button> <button style={{background:"#101217",border:"1px solid #30343c",color:"#b9bfca",padding:"10px 13px",borderRadius:9,marginLeft:8}}>♡ Save tool</button></div></div><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 240px",gap:70,paddingTop:48}}><article><h2>Overview</h2><p style={{color:"#969daa",lineHeight:1.75}}>A curated business-AI recommendation for teams that want to spend less time on repetitive work and more time on high-value outcomes.</p><h2 style={{marginTop:36}}>Key capabilities</h2><ul style={{listStyle:"none",padding:0,lineHeight:2.4,color:"#c3c7cf"}}>{tool.features.map(x=><li key={x}><b style={{color:"#9b8cff",marginRight:10}}>✦</b>{x}</li>)}</ul></article><aside style={{background:"#101217",border:"1px solid #282c34",borderRadius:12,padding:18,height:"max-content"}}><small style={{color:"#777e8b",letterSpacing:".1em"}}>PRICING</small><p className={tool.pricing.toLowerCase()} style={{fontWeight:700}}>● {tool.pricing}</p><hr style={{borderColor:"#242830"}}/><small style={{color:"#777e8b",letterSpacing:".1em"}}>AVAILABILITY</small><p>Web app · API available</p></aside></div></section></main>}
